name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on:  integration platform for Kubernetes-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi!👋\nThank you for raising the issue.\nWe hope you like the Devtron Labs toolkit!\nWe will investigate your issue as soon as possible."
        pr-message: "Hi!👋\nThank you for the Pull Request 💖.\nPlease read [CONTRIBUTING.md](https://github.com/devtron-labs/hacktoberfest2022/blob/main/Docs/doc-contribution-guidelines.md) to make a good PR."
